
#### general settings

name: 01_IDCNN_GAN_DB_l2l1_new_f2_x4_scratch_DIV2K

use_tb_logger: true

model: invgan-sr

distortion: sr

scale: 4

gpu_ids: [0]



#### DIV2K

# mean: [0.44845608, 0.43749626, 0.40452776]

# std: [0.27890206, 0.2646495 , 0.28554508]





r_mean: 0.44845608

g_mean: 0.43749626

b_mean: 0.40452776

r_std: 0.27890206

g_std: 0.2646495

b_std: 0.28554508



#### datasets

datasets:

  train:

    name: DIV2K

    mode: LQGT

    dataroot_GT: /home/shuxin/data/DIV2K/DIV2K_train_HR.lmdb

    dataroot_LQ: /home/shuxin/data/DIV2K/DIV2K_train_LR_bicubic/X4.lmdb





    use_shuffle: true

    n_workers: 6  # per GPU

    batch_size: 16

    GT_size: 144

    use_flip: true

    use_rot: true

    color: RGB

  val:

    name: val_DIV2K

    mode: LQGT

    dataroot_GT: /home/shuxin/data/DIV2K/DIV2K_valid_HR.lmdb

    dataroot_LQ: /home/shuxin/data/DIV2K/DIV2K_valid_LR_bicubic/X4.lmdb



#### network structures

network_G:

  which_model_G:
      block_type: InvBlockExp
      subnet_type: DBNet

  in_nc: 3

  out_nc: 3

  block_num: [0, 8, 8]

  scale: 4

  init: xavier

network_D:

  which_model_D: discriminator_vgg_128

  in_nc: 3

  nf: 64



#### path

path:

  pretrain_model_G: /home/mingqing/InvSR/experiments/pretrained_models/IDCNN.pth

  strict_load: true

  resume_state: ~



#### training settings: learning rate scheme, loss

train:

  lr_G: !!float 1e-4

  beta1: 0.9

  beta2: 0.999

  niter: 400000

  warmup_iter: -1  # no warm up



  lr_scheme: MultiStepLR



  lr_steps: [50000, 100000, 200000, 300000]

  lr_gamma: 0.5



  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  feature_criterion: l1

  feature_weight: 1



  manual_seed: 10

  val_freq: !!float 5e3


  lambda_fit_forw: 16

  lambda_rec_back: 0.01

  lambda_mle_forw: 0

  gradient_clipping: 10

  weight_decay_G: !!float 1e-5


  lr_D: !!float 1e-4

  weight_decay_D: 0

  beta1_D: 0.9

  beta2_D: 0.99

  gan_type: gan

  gan_weight: !!float 0.1

  D_update_ratio: 1
  D_init_iters: 5000


#### logger

logger:

  print_freq: 100

  save_checkpoint_freq: !!float 5e3
