# Not exactly the same as SRResNet in <Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network>

# With 16 Residual blocks w/o BN



#### general settings

name: 000_InvbiGANFeatureExpSigmoidRRDBNetInitXavier_wd_nommd_mle_learnedy_block16_l2_mle_x4_scratch_DIV2K

use_tb_logger: true

model: invganbi-sr

distortion: sr

scale: 4

gpu_ids: [3]



#### DIV2K

# mean: [0.44845608, 0.43749626, 0.40452776]

# std: [0.27890206, 0.2646495 , 0.28554508]





r_mean: 0.44845608

g_mean: 0.43749626

b_mean: 0.40452776

r_std: 0.27890206

g_std: 0.2646495

b_std: 0.28554508



#### datasets

datasets:

  train:

    name: DIV2K

    mode: LQGT

    dataroot_GT: /home/shuxin/data/DIV2K/DIV2K_train_HR.lmdb

    dataroot_LQ: /home/shuxin/data/DIV2K/DIV2K_train_LR_bicubic/X4.lmdb





    use_shuffle: true

    n_workers: 6  # per GPU

    batch_size: 16

    GT_size: 144

    use_flip: true

    use_rot: true

    color: RGB

  val:

    name: val_DIV2K

    mode: LQGT

    dataroot_GT: /home/shuxin/data/DIV2K/DIV2K_valid_HR.lmdb

    dataroot_LQ: /home/shuxin/data/DIV2K/DIV2K_valid_LR_bicubic/X4.lmdb



#### network structures

network_G:

  which_model_G: InvExpSigmoidRRDBNet

  in_nc: 3

  out_nc: 3

  block_num: [0, 8, 8]

  scale: 4

  init: xavier

network_D:

  which_model_D: discriminator_vgg_128

  in_nc: 3

  nf: 64

forward_discriminator:
  network_D:

    which_model_D: discriminator_vgg_32

    in_nc: 48

    nf: 64



#### path

path:

  pretrain_model_G: /home/mingqing/InvSR/experiments/pretrained_models/85000_G.pth

  strict_load: true

  resume_state: ~



#### training settings: learning rate scheme, loss

train:

  lr_G: !!float 1e-4

  beta1: 0.9

  beta2: 0.999

  niter: 400000

  warmup_iter: -1  # no warm up



  lr_scheme: MultiStepLR



  lr_steps: [50000, 100000, 200000, 300000]

  lr_gamma: 0.5



  pixel_criterion: l2

  feature_criterion: l2

  feature_weight: 1



  manual_seed: 10

  val_freq: !!float 5e3


  lambda_fit_forw: 16

  lambda_mle_forw: 1

  lambda_rec_back: 0.01

  gradient_clipping: 10

  weight_decay_G: !!float 1e-5

  use_learned_y: True


  lr_D: !!float 1e-4

  weight_decay_D: 0

  beta1_D: 0.9

  beta2_D: 0.99

  gan_type: gan

  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0


  lr_D_forw: !!float 1e-4

  weight_decay_D_forw: 0

  beta1_D_forw: 0.9

  beta2_D_forw: 0.99

  gan_type_forw: gan

  gan_weight_forw: !!float 5e-3


#### logger

logger:

  print_freq: 100

  save_checkpoint_freq: !!float 5e3
